const Appreciation = "Appreciation"
const FeelingGrounded = "FeelingGrounded"
const HouseholdItems = "HouseholdItems"
const HumanConnection = "HumanConnection"
const Perseverance = "Perseverance"

export const photos = [
  {
    title: "Animal Crossing",
    src: "images/animal_crossing.png",
    thumbnail: "images/animal_crossing.png",
    audioSource: "",
    themes: { Appreciation },
    transcript: "yay animal crossing",
    textSubmission: true,
  },
  {
    src: "images/ballgame.jpg",
    thumbnail: "images/ballgame.jpg",
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },
  {
    src: "images/basketball.jpg",
    thumbnail: "images/basketball.jpg",
    audioSource: "audioStory/gtmt-wqpp.mp3",
    themes: {},
    transcript: "",
    textSubmission: false,
  },
  {
    src: "images/bathroom.jpg",
    thumbnail: "images/bathroom.jpg",
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },
  {
    src: "images/bicycle.png",
    thumbnail: "images/bicycle.png",
    audioSource: "",
    themes: {},
    transcript: "",
  },
  {
    src: "images/birthday.png",
    thumbnail: "images/birthday.png",
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },
  {
    title: "Candles",
    src: "images/candles.jpg",
    thumbnail: "images/candles.jpg",
    transcript:
      "Since quarantine started, I started to spend a lot more time in my room and in like my personal spaces, and a lot of that  was creating a space. I was then encouraged to create a space that felt really personal to me and like welcoming and homey because if I was going to be spending that much time at like my desk for instance, I wanted to make sure that I was comfortable there. And, I've always really liked candles. I find them to be extremely calming, and I think that the light they emit is really beautiful. Very different than a lot of the harsh lights that I'm looking at on my computer all day and those sort of things. And the kind of warmth they give off also brings me a lot of joy and happiness. So, once I was getting settled in my St. Louis apartment, I spent a couple trips going to Target with my roommates to pick out various items, and I never went in with the intention of buying a candle but somehow always walked out with one and started building up a small collection in my apartment. I think in terms of the word 'Grounded' these things really do provide me with a sense of groundedness, and when I feel like when I light them, I have no choice but to be calm because the candle itself represents this calmness and especially with all these crazy things going on in the world - their nature of being illuminating and providing light in the darkness and calm in the eye of the storm and that sort of thing. I just started to build a deeper and deeper connection. And now every time I walk in my room, every time I sit down to do work, I reach for my lighter and I light a candle and leave it burning for probably a little too long. And it's brought me a lot of joy in these very confusing times and has allowed me to create spaces I feel comfortable in, especially because I spend so much time in them.",
    audioSource: "Audio/candles.mp3",
    themes: { FeelingGrounded, HouseholdItems },
    textSubmission: false,
  },
  {
    title: "Harry Potter book",
    src: "images/harry_potter_book.jpg",
    thumbnail: "images/harry_potter_book.jpg",
    audioSource: "Audio/harry_potter_book.mp3",
    transcript:
      "While choosing Harry Potter 7 as my artifact is sort of a basic response to this prompt. Reading *Harry Potter and the Deathly Hallows* was a really meaningful experience to me over quarantine and since the time the pandemic began. I actually didn't enter the Harry Potter game until a little bit later in my life. And by the time I entered high school, I was reading the fifth, and my mom just thought I was too old to be reading it, so I moved onto kind of more adult books at that time, and then came college, I still hadn't read the sixth or seventh book, which is crazy. And finally in quarantine, I really had a time to sit down and read. I didn't have anything else to do really, so it was my first time reading it. And although I wish I read *Harry Potter and the Deathly Hallows* when I was younger, I absolutely loved reading it at age 21. And during such a stagnant time in the world, I felt like a kid again in my childhood house rather than this like 21 year old transplant at home. I was totally engrossed with the book. And just super absorbed. Staying up until 3am reading not knowing where the time went - what a wonderful experience that I haven't had in a really long time. It just like brought me a lot of happiness and most importantly, it was just like this amazing escape. You know reading that book and turning the pages, not knowing the time, not knowing where I was in the story - just fully living in this other world and universe and escaping the one we are currently in. So, it just - I hadn't felt like that in a while, and I think it meant more to me than ever because in a time where there's so much turmoil in the world, it felt really refreshing to sort of exit it for a moment. And just to have that outlet that was fun and creative and magical. I think in the end because it was so special and so fun, and I loved the book so much, that it allowed me to appreciate this downtime that we have. And I'm privileged in saying that because I know how difficult this has been for so many people on a way more intense scale than it has been for me. But I think in sitting and reflecting and relaxing and having a moment to breathe, and just pick up Harry Potter 7 and tear through it and have fun - I felt very appreciative of that bonus time.",
    themes: { Appreciation },
    textSubmission: false,
  },
  {
    src: "images/lanterns.jpg",
    thumbnail: "images/lanterns.jpg",
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },
  {
    title: "Lanyard",
    src: "images/lanyard.webp",
    thumbnail: "images/lanyard.webp",
    audioSource: "Audio/lanyard.mp3",
    transcript:
      "This item is the lanyard of my work badge. This item has gained importance to me during the pandemic because it taught me to be thankful that I have a job when so many others are in need and do not have a job.",
    themes: { Perseverance, Appreciation },
    textSubmission: false,
  },

  {
    src: "images/laptop.jpg",
    thumbnail: "images/laptop.jpg",
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },

  {
    src: "images/library.jpg",
    thumbnail: "images/library.jpg",
    audioSource: "audioStory/wawy-oum2.mp3",
    themes: {},
    transcript: "",
    textSubmission: false,
  },
  {
    src: "images/lime_glass.png",
    thumbnail: "images/lime_glass.png",
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },
  {
    src: "images/machinery.jpg",
    thumbnail: "images/machinery.jpg",
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },

  {
    title: "Mountain Dew",
    src: "images/mountain_dew.png",
    thumbnail: "images/mountain_dew.png",
    audioSource: "Audio/mountain_dew.mp3",
    transcript:
      "This five month old can of Mountain Dew Game Fuel I got from engineering a while back, and I don't think this can of Mountain Dew Game Fuel really means anything and I don't think there is anything really profound connected to it. But, I have been thinking of doing something with this packaging and design and, to me, it does feel like a part of WashU that I just haven't touched. Although, I have kind of wandered around campus after school closed. It's very empty and I've been trying to think about how I can continue to make things that are meaningful during quarantine that don't take away from the very important conversation that we are having right now and that kind of dialogue. So yeah. It's weird taking in all that is going on but I've been trying to process it in different ways that help us focus on what's important.",
    themes: { Perseverance, HouseholdItems },
    textSubmission: false,
  },
  {
    title: "Office Home",
    src: "images/office_home.jpg",
    thumbnail: "images/office_home.jpg",
    audioSource: "Audio/office_home.mp3",
    themes: { HumanConnection, HouseholdItems, Perseverance },
    transcript:
      "You know before saying anything, I think it's important to note that, at a time when hundreds of thousands of Americans have died and millions have lost their jobs, I'm extraordinarily lucky to be healthy and employed and you know, folks like me who have been lucky enough to not be personally affected by the Coronavirus, and have jobs and can work from home. One of the biggest difficulties has been the blurring of the line between personal and professional life. Right, um, gone is the daily commute to collect your thoughts on your way to work and personal interactions with your coworkers, the physical distinction of leaving work for the day and being done. And so, with these distinctions gone, everything just sort of bleeds together. You know, work and personal become one and days blend together and slowly blend into weeks. But, you know, as stressful and disorienting as this often is, it's still so removed from the pain and suffering that this pandemic has caused. And, this really hit home last week when on a call from work, we had heard from a local doctor and he was talking about the lived reality of the reason that we are all at home. You know, all this stress about these blurred days just kind of came crashing in as– or crashing away as he described seeing the most death he's seen in his time as a doctor. And it really makes the problem of working at home seem so small and insignificant when you know that that's really what's happening out there and, I don't know, this whole thing's very strange but for as long as this stays our reality people are gonna... You know I’ll keep working at this plastic desk next to my bed and doing what I can to protect those more vulnerable than myself.",
    textSubmission: false,
  },
  {
    src: "images/orange.jpg",
    thumbnail: "images/orange.jpg",
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },

  {
    title: "Pebble",
    src: "images/pebble.png",
    thumbnail: "images/pebble.png",
    thumbnailWidth: 345.9,
    thumbnailHeight: 343.2,
    audioSource: "Audio/pebble.mp3",
    themes: { FeelingGrounded, Perseverance },
    transcript:
      "Alright, well, there's a lot that's happened over the past few months. There's always a lot going on, and it always seems like there's fifty awful things that are happening outside my home, and it's hard not to feel like I need to engage with them in some way. Yet, whenever I do or whenever many of the people around me do, it's overwhelming, and it can feel like there's nothing really good going on, anything really anchoring us. So, there's this rock that I have. It's smooth. It's about the size of a few quarters. It's a river pebble. It's grey. It's kind of marbled. You look at it and you sort of see another layer to it, like there's the surface and then the longer you look at it, the more you see– the more cracks and ridges you see kind of going away into the depths. And, it's really calming to hold. It feels like something hard and certain is there. And, it's just the right size for you to hold in your hand and fidget with. Whether I am sitting somewhere, like in a meeting, or just anything really. When anything stressful is going on it's become a habit to take this rock and just to hold it and it's relaxing. It really does wonders, I think. And, I'm glad that there's something, just one thing, right now that's certain like just this tiny rock that somehow makes all the difference for me to focus on and and, for a moment, stop thinking about the virus, stop thinking about all the violence that's occurring right now about all of these larger things that I feel like I have no control over, and just center myself on just a rock that I just picked up somewhere. I don't even remember where I have it from. And yet, it does it's job, really. I hope that others have also been able to find something like this for themselves and be able to take on a new meaning in a time when really all of us need something to help ground ourselves.",
    textSubmission: false,
  },
  {
    src: "images/pet_rat.jpg",
    thumbnail: "images/pet_rat.jpg",
    thumbnailWidth: 320,
    thumbnailHeight: 240,
    audioSource: "",
    themes: {},
    transcript: "",
    textSubmission: false,
  },
  {
    title: "Recipes",
    src: "images/phone.webp",
    thumbnail: "images/phone.webp",
    thumbnailWidth: 251.9,
    thumbnailHeight: 256.2,
    audioSource: "audioStory/rszf-508l.mp3",
    transcript:
      "Speaker 1: So mommy, can you tell me about an object or an activity or something that has been especially meaningful to you during this time that we've spent at home during this pandemic? <br></br> Speaker 2: Yeah. Recently, I have started to work on my YouTube blog, which is a cooking channel. I started this even before the COVID-19 had come up. But this COVID-19 had given me a lot of time to cook new dishes for my kids. So I was experimenting a lot. And it came up very well. And my kids were happy too. And I was happy to make them nice dishes for them. <br></br> Speaker 1: And can you tell us about some of those, I guess, hawker food dishes like hokkien mee and bee hoon that traditionally, we would go and eat at a hawker center. But you figured out how to make that.<br><br> Speaker 2: Because during COVID-19 situation, I thought it's not that safe for that safe for our family to go out and have dinner. So usually, I came up with some new recipes that my kids would like to eat. So luckily, I had a Malaysian friend. So I used to always refer to her for some help on making some new recipes, like hokkien mee and bee hoon. And she was very good in all those, and she gave me some ideas how to work on it. So I tried, and it was really a very good dish that came out and my family liked it. So I was very happy about it when my family enjoyed eating them. So and it has deliberately become very important, very important dish in our meal plan. So it is wonderful. <br></br> Speaker 2: Because during COVID-19 situation, I thought it's not that safe for that safe for our family to go out and have dinner. So usually, I came up with some new recipes that my kids would like to eat. So luckily, I had a Malaysian friend. So I used to always refer to her for some help on making some new recipes, like hokkien mee and bee hoon. And she was very good in all those, and she gave me some ideas how to work on it. So I tried, and it was really a very good dish that came out and my family liked it. So I was very happy about it when my family enjoyed eating them. So and it has deliberately become very important, very important dish in our meal plan. So it is wonderful. <br></br> Speaker 2: I will not say it was same because when everybody or home, I think the workload was getting a bit more on me. So I tried to manage my time, it helped me to do more of meal planning for my kids so that they eat healthily. So I used to meal plan and see that my kids have a wholesome meal, they are eating healthily. And I was able to see that they had taken on time. As soon as during this time, I used to always experiment doing lot of new recipes. This enhanced my cooking skills. And I also it like it opened my eyes that what I knew before was not enough. And there are so much things to learn. Cooking is a vast area where you can learn new things, as well as the experiment with it. And it's a lot of fun doing that. <br></br> Speaker 1: And I guess we're very lucky that, well, I can't really cook. But I did teach you some of the things that I learned how to cook from my friends. <br></br> Speaker 2: Yeah, actually, you're very good at baking. And that's a thing that you really enjoy to do. Actually, I, in the beginning to say the truth, I didn't have much interest in baking. But after my daughter joined me, I started to learn from her know how to bake things. And now I'm doing better than her hopefully I think so. <br></br> Speaker 2: Yeah, actually, you're very good at baking. And that's a thing that you really enjoy to do. Actually, I, in the beginning to say the truth, I didn't have much interest in baking. But after my daughter joined me, I started to learn from her know how to bake things. And now I'm doing better than her hopefully I think so. <br></br> Speaker 2: Yeah, actually, you're very good at baking. And that's a thing that you really enjoy to do. Actually, I, in the beginning to say the truth, I didn't have much interest in baking. But after my daughter joined me, I started to learn from her know how to bake things. And now I'm doing better than her hopefully I think so. <br></br> Speaker 1: So I guess someone's calling in. But thank you, mommy for for adding your story to this archive. <br></br> Speaker 2: Thank you. Thank you so much.",
    themes: { HumanConnection },
    textSubmission: false,
  },
  {
    title: "Plant Vase",
    src: "images/plant_vase.jpg",
    thumbnail: "images/plant_vase.jpg",
    thumbnailWidth: 302.4,
    thumbnailHeight: 403.2,
    audioSource: "Audio/plant_vase.mp3",
    themes: { Appreciation, Perseverance, HouseholdItems },
    transcript:
      "So I bought this plant last September.[and] at the time, it was blooming these really bright yellow flowers.  It was really beautiful but when I went abroad in the spring, I had to leave it with one of my roommates so that he could take care of it until I got back.  But of course when the pandemic hit, he couldn’t go back to the dorm so the plant was left there, untouched and in the dark for about four months.  You would think that when my roommate went back to get his things from our dorm in June, the plant would have been completely dried out and withered. I actually think we had both probably forgotten about it by then. But even though the plant was in pretty rough shape, there was definitely some green hiding under there.  So I pulled off the leaves and I gave it some water and put it on a windowsill and a few weeks later, it actually looked healthy again and has since grown quite a bit. And I really wouldn’t be surprised if it starts blooming again sometime soon.  This plant is a fighter I would say, and I know this time has been hard on everyone: some more than others. But I think that we all just kind of need to hold a little longer and, I don’t know, I’m feeling very hopeful.",
    textSubmission: false,
  },
  {
    title: "Punching bag",
    src: "images/punching_bag.jpg",
    thumbnail: "images/punching_bag.jpg",
    thumbnailWidth: 302.4,
    thumbnailHeight: 403.2,
    audioSource: "Audio/punching_bag.mp3",
    themes: [Perseverance, HouseholdItems, Appreciation],
    transcript:
      "So the object that I chose to talk about is the punching bag that hangs in my basement in my childhood home. And, I never really paid attention to it until I found myself quarantined in the basement and dealing with a lot of negative emotions after coming back from being abroad and feeling frustrated, uncertain, lonely, and wondering why all this was happening. So, one day, on a whim, I decided to try hitting the punching bag. I was really bad at it at first, but eventually, as I kept going, I was able to put more and more power into my punches and channel all of my negative sentiments into this physical outlet. Hitting the punching bag became a part of my weekly routine and it became a cathartic way for me to kind of reset for my week and remind myself that there are things that I can control— little things I can do, including, staying in touch and controlling my attitude and my emotions.",
    textSubmission: false,
  },
  {
    title: "Quilt blanket",
    src: "images/quilt_blanket.jpg",
    thumbnail: "images/quilt_blanket.jpg",
    thumbnailWidth: 302.4,
    thumbnailHeight: 403.2,
    audioSource: "audioStory/1tw5-x3dg.mp3",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
  {
    title: "Sanitizer",
    src: "images/sanitizer.webp",
    thumbnail: "images/sanitizer.webp",
    thumbnailWidth: 247.4,
    thumbnailHeight: 338.1,
    audioSource: "Audio/sanitizer.mp3",
    themes: { HouseholdItems, HumanConnection },
    transcript:
      "So I ended up taking a picture of this little bottle of hand sanitizer and the reason I chose it was because I really feel that it’s kind of a symptom; it reminds kind of how everything has changed in the world in terms of public spots and hygiene and all that.  At least to me, I feel like it will be hard for me, at least mentally, to go back to the way things were.  I feel like I don’t know if I can even see crowded concert venues, crowded sidewalks and streets and doors and all that kind of stuff the same way again; just knowing how much the germs and how unhygienic it can be. And it’s just crazy how we took so much of that stuff; we just kind of put it under the rug more or less and just kind of went about our lives.  When in reality it's just been a massive breeding ground for who knows what so, yeah. This tiny little bottle of sanitizer reminds me of that whole movement, the whole kind of way everything has changed now and the fact, that I have one in my room, that I carry it around everywhere when I go outside. A little bottle just, you know, I feel like for me it’s just a lot. I feel like again just changed everything. And the fact that even these kinds of things are so hard to find now. It’s even more telling of the times and how, as a society we’ve been really unprepared for this whole pandemic and how there’s a lot of change that needs to happen if we are to prevent this kind of thing from happening again.",
    textSubmission: false,
  },
  {
    title: "Scrabble",
    src: "images/scrabble.jpg",
    thumbnail: "images/scrabble.jpg",
    thumbnailWidth: 403.2,
    thumbnailHeight: 196,
    audioSource: "Audio/scrabble.mp3",
    themes: {
      Appreciation,
      HouseholdItems,
      HumanConnection,
    },
    transcript:
      "The picture is of our Scrabble set. And, you know, I could only open up the little books that we've been using to certain pages. And it's funny because they happen to show me winning two out of the three games pictured. But the fact is my son who had to come home from college, during the lockdown, you know, came home early came home in March, he's 19. He and I have played probably 100 games of Scrabble. Since mid March, maybe more, probably 85% of the time he wins. That picture shows me winning a few times there. But it's just been this wonderful bonding experience. You know, we always love to play Scrabble, but the amount of games we've played, and how it's become a routine, and you know, a time to really just forget, for a few minutes about everything that's going on and just focus completely on the moment and the game. We put our phones aside, we just really enjoy the game and I seem to have reached more of a plateau with my ability to score, he keeps getting better and better. And he plays online. And, you know, he's talking about when he does go back to college, even though he's deferring his sophomore year for now, because of Coronavirus concerns and restrictions at the school, not wanting to take classes online etc. But you know, he is talking about starting a Scrabble club back at school because it has been, it's just, we both feel it is a perfect game. But it is a symbol of the amount of family time and time at home and time to have basic simple pleasures mean more in life for a lot of people, certainly for us. You know he's been, you know, just taking the time to explore some things that he loves that, you know, when he's socializing, or at school taking classes or you know, just when everything is open and normal - he doesn't have as much time to do, and I have found the same for myself, you know, I've gotten back to reading again, which for some reason I had not doing enough of you know. And just appreciating simple conversation again, and just lovely aspects of, of being, you know, tied to other human beings that are right there in our lives instead of the humans that are out there on the internet or, you know, people we don't know, but for some reason we listen to and get, you know, worked up about. And it's really, it's really, this time is really about family, and about the people you love and the people who support you in tough times and the people who turn to you in tough times. And for some reason, this picture of the Scrabble set captures that for me. And I don't know what I would do what I would have done during this time, if not for my two sons, who, again, we have leaned on each other. We support each other through what's you know, unprecedented time in history. And I just, you know, reminded again and again, how much I love them and I'm so grateful for them.",
    textSubmission: false,
  },
  {
    title: "Scrapbook",
    src: "images/scrapbook.jpg",
    thumbnail: "images/scrapbook.jpg",
    thumbnailWidth: 302.4,
    thumbnailHeight: 403.2,
    audioSource: "Audio/scrapbook.mp3",
    themes: { FeelingGrounded },
    transcript:
      "This artifact is a journal full of collages that I made throughout quarantine and was a simultaneously very grounding factor for me, but also became this way to sort of track the time and encapsulate all of the feelings in this weird weightlessness that you felt, that I felt, during this time in a very tangible and tactile sort of way. I got this journal when I was abroad in Copenhagen and didn't really do much with it there it kind of free journal. I picked it up and kind of sat on shelf for the entire time that I was there. But also, while I was in Copenhagen, I did a lot of collecting of papers and ticket stubs and pamphlets. And those were my souvenirs from the trips that I was able to take. And also kind of they sat in a little pile, not really sure what I was going to do with them. But they felt important, I didn't want to throw them away. So then, when we had a huge reversal of life course, and I abruptly left Denmark and arrived at home, very, very sick. It I just felt like I was in limbo this entire time. I didn't know, I felt like I didn't have a grasp of what was happening around me. It felt like I was floating. But after recovering and sitting at the breakfast table for the first time confirmed that I was no longer sick, and our family was kind of experiencing what was becoming to be our Sunday routine of just sitting on the couch together and having a lazy morning. My dad gave me a section of the Wall Street Journal, which it was just funny coming from the Wall Street Journal and it's like this section is off duty section where they have things on food and style and whatever from their culture curators. And he was like, I found this for you, I thought you'd like it. And I was really touched that he did that and was just piecing through what was in there and realized that there was a lot of really cool visual elements to that and then dusted off this journal from my still unpacked bags from abroad. And also then began going through those papers that I had been set aside and put away and seeing how the elements from the newspaper at home fit with the elements that I had brought back. And the act of just putting them together helped, was a sense making activity for me. And the classes were never meant to be good. They were just meant to be an exercise. And the one that's pictured was special to me because it was from a off duty section that came around right around graduation time for the 2020 grads and they ended up posting a whole collection of commencement speeches from various people in this newspaper article. And reading through those was just inspiring and an act of hope, and I wanted to make sure that there was a way that I could put that on paper and remember it and it's something that I looked back to even now.",
    textSubmission: false,
  },
  {
    title: "Screen",
    src: "images/screen.jpg",
    thumbnail: "images/screen.jpg",
    thumbnailWidth: 403.2,
    thumbnailHeight: 302.4,
    audioSource: "",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
  {
    title: "Snoopy",
    src: "images/snoopy.png",
    thumbnail: "images/snoopy.png",
    thumbnailWidth: 240,
    thumbnailHeight: 240,
    audioSource: "",
    themes: [HumanConnection],
    transcript:
      "I miss those euphoric crowd sing alongs. Dancing in a sea of people. Discovering new music acts to love. The indescribable connection between fans.",
    textSubmission: true,
  },
  {
    title: "Air Plant",
    src: "images/spiky_plant.webp",
    thumbnail: "images/spiky_plant.webp",
    thumbnailWidth: 302.4,
    thumbnailHeight: 290.4,
    audioSource: "Audio/spiky_plant.mp3",
    themes: { FeelingGrounded, Perseverance },
    transcript:
      "Speaker 1: This little guy is called an air plant, which is a gift that my dad gave to me right at the beginning of the pandemic when I was forced to go home from school. And basically, it's like a succulent. But it's really, I've been really drawn to it in the past few months, A because I think having some some green space inside is very important when we're all stuck inside, but also because it's this little tiny plant. And it's probably about two inches, maybe three inches wide. And how you water it is once every two weeks or so, you soak it under water for about an hour, and then you dry it upside down and then you put it back in the planter. And just sort of this process of becoming subsumed in water and then subsequently hanging upside down, drying out and then going back into your place -- It really has just felt like a metaphor for our lives right now. And the little guy just keeps going. And I really just feel sort of grounded and also inspired by the imagination of myself kind of falling under water and then coming back up and figuring my way out of this strange, strange world we're living in right now.",
    textSubmission: false,
  },
  {
    title: "Spongebob Cup",
    src: "images/spongebob.webp",
    thumbnail: "images/spongebob.webp",
    thumbnailWidth: 285.8,
    thumbnailHeight: 492.2,
    audioSource: "Audio/spongebob.mp3",
    themes: {
      Perseverance,
      HouseholdItems,
      HumanConnection,
      Appreciation,
    },
    transcript:
      "So I got this holographic SpongeBob cup from Universal Studios Los Angeles when I was probably around seven years old. At the time, I didn't live in LA. So, um, it was a nice, you know, special outing. And you know, when you go to an amusement park or something with your parents, you always have to buy one souvenir. Well, I'm a huge SpongeBob fan. So at the time, me and my brother decided that the one like souvenir we wanted from Universal Studios was these holographic cups. Um, so basically, we used to pretty much daily–every morning, my mom, she would make us a smoothie. And she would put him most of the time in our matching SpongeBob cups. We had two one for me, one for my brother. Um, and as I grew older, I guess it kind of just sat in my cabinet. But as I was packing up for college, I saw my two SpongeBob cups and I was like, f**k it, I'm gonna bring my holographic SpongeBob cup to college. And basically, it was my main pregame cup. Whenever, you know, I was drinking to go out, I would put my alcohol in my SpongeBob cup. But I guess fast forwarding to now in the pandemic. I was living at home and you know, doing work, which was a different dynamic. I haven't experienced it since high school, or I guess I really haven't experienced it at all. Because you know, you're doing work while in your home, you're going class while in your home. So my mom was really sweet. She would, you know, bring me my breakfast to my room every day. I was two hours earlier for my timezone. So I had to wake up really early, she would make me my breakfast. And almost every day, she would bring me my smoothie in my SpongeBob cup. I guess shifting gears a little bit. So now at this point, I always had one at college and one at home. And when I came back to my dorm room around June, it looked like you know, it was a pause any random moment in time it looked like, you know, we all escaped to go to a bomb shelter, like no one had cleaned up everything it was walking back into that room was so weird. But my SpongeBob Cup was sitting on my desk. And I was like, I almost forgot that, you know, I had one here at college since, you know, I'd been using it so much at home. But now, okay, sorry, I feel like this is really long. But basically I've been using it every day now as my water cup. I'm no longer living with my mom. And I'm too lazy to make smoothies myself every morning. So I put my water in my SpongeBob cup. And it sits on my desk all day. So now rather than just using it in the morning, I'm drinking water from it every single day and I just kind of look at it. I think to myself, like when I bought this cup when I was seven years old, I could I have anticipated that 14 almost 15 years later, I would still be using it pretty much daily? That this is maybe one of the most old and like well used objects I've ever owned in my life? And that was just something that I started thinking about during quarantine. You know, I finally started staring my SpongeBob cup in the face and realizing huh like at the time when I bought this I had no clue that it would garner so much meaning or even be around still using it.",
    textSubmission: false,
  },
  {
    title: "Sunset",
    src: "images/sunset.jpg",
    thumbnail: "images/sunset.jpg",
    thumbnailWidth: 403.2,
    thumbnailHeight: 302.4,
    audioSource: "Audio/sunset.mp3",
    themes: { Appreciation, FeelingGrounded, HumanConnection },
    transcript:
      "All right, hello! So this is a picture of a sunset at a park that I took one night, a couple of weeks ago, I was on a masked and socially distanced walk with a very dear friend of mine who I don't get to see too often. But when we see each other, it just feels like the stars are aligned, and that the world will be okay again, once more. So I think being in nature overall, has been something that has kept me very much grounded throughout this whole quarantine. Um, so I haven't really stepped foot inside of a building in several months. And that was a big change for me, especially still being in my hometown right now in Ohio. One of the things I would do to hang out with people is just to go inside a Target or probe, just walk around, you know, browsing nothing, yet browsing everything at once, eyeing the clearance shelf, but never actually buy anything from it. Oh, yeah, those were the days. But clearly, that is not really an option for us now, or I guess it's not really a safe option. So instead, I've been spending a lot of time outdoors a lot with my family, and in particular, my dad and my sister when she was home. And those were times that I never really realized that I needed. I think before and years of my life, I hadn't really spent a lot of time with my family as already, I was always out and about doing some other things or trying to hang out with friends other than family. And I guess it wasn't really until this pandemic that I realized how important my family really is to me, even though they perhaps aren't who I go to for emotional support, or certain other kinds of advice or support that I would like. They're still people that I hold extremely, extremely close to my heart and that, I know, unconditionally love and care for me. I'll be in different ways than perhaps some friends you know, but I am very lucky to have a really great family who does support my endeavors. I'm really, really grateful to have such amazing people in my life I think. This is something else that I've thought about a lot in quarantine -- how sometimes it just really feels like I won Lice lottery, as a friend had once described to me. I've been fortunate. I am fortunate enough to be able to venture outside and spend time in nature. You know, not everyone has the privilege of doing so. Not everyone is able to access those kinds of things that I am. So I think I'm just I've developed a very strong sense of gratitude, I think for everything in my life, everything and everyone in my life. I've been fortunate enough to still be able to call friends, and I've still been able to make new friends and strengthen friendships over the past couple months, even though I haven't really seen people outside of my family in quite a while. But even though I really do miss human interaction, I think that's largely because I'm a pretty physically affectionate person. I really do love hugs. The only being or entity that I really hugged the past few months is my dog who I love very much. We've gotten very tight. I was always his favorite, but then I went to college. And then I think he forgot that I was his favorite when I first came back, but now he remembers again, so that's perfectly okay. But I'm just very, very grateful for all that has come into my life. And I think heights has been something that, when I do on the rare occasion go out on a walk or hike with a friend, that's something that keeps me grounded. I always feel so... reinvigorated after going on hikes with friends, you know. I think I derive a lot of my happiness from being around people. And nature has allowed me to do that. And I'm extremely, extremely grateful that I just been able to have such great access. Plug for Ohio -- we have a lot of parts, and they're really really pretty parks too. Although I guess it's just nature around, nature to me is quite beautiful. And now I have been rambling on for some time, so thank you so much for listening. If anyone has gotten this far, I appreciate you all a lot. And yeah, remember to tell your loved ones that you love them in however whatever way that looks to you. It looks different for everyone. And I hope you all are doing okay, whoever hears this. And remember that you are loved and cared for, even if it feels like you are not.",
    textSubmission: false,
  },
  {
    title: "Transit Card",
    src: "images/transit_card.webp",
    thumbnail: "images/transit_card.webp",
    thumbnailWidth: 403.2,
    thumbnailHeight: 249,
    audioSource: "Audio/transit_card.mp3",
    themes: { Appreciation },
    transcript:
      "June 2020 was the first month in over four years that I haven't auto-renewed my unlimited ride New York City metro pass. Riding the subways was a big part of my experience living in New York City. I'd ride multiple times a day. I relied on the ease and convenience so much that I never even considered not paying for an unlimited pass. But in early May, my employer told us that we should expect to work remotely and won't be able to return to our office in downtown Manhattan until 2021. I finally had to cancel my Metro pass. And I have no idea when I'll start commuting and using the subway again for it to make sense for you to get another.",
    textSubmission: false,
  },

  {
    title: "Wall Art",
    src: "images/wall_art.jpg",
    thumbnail: "images/wall_art.jpg",
    thumbnailWidth: 403.2,
    thumbnailHeight: 302.4,
    audioSource: "",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
  {
    title: "WashU",
    src: "images/washU.png",
    thumbnail: "images/washU.png",
    thumbnailWidth: 420,
    thumbnailHeight: 270.2,
    audioSource: "",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
  {
    title: "WashU",
    src: "images/washU1.png",
    thumbnail: "images/washU1.png",
    thumbnailWidth: 420,
    thumbnailHeight: 270.2,
    audioSource: "audioStory/iofa-etp6.mp3",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
  {
    title: "WashU",
    src: "images/washU2.png",
    thumbnail: "images/washU2.png",
    thumbnailWidth: 420,
    thumbnailHeight: 270.2,
    audioSource: "audioStory/ndsw-3x8j.mp3",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
  {
    title: "Watch",
    src: "images/watch.webp",
    thumbnail: "images/watch.webp",
    thumbnailWidth: 374.7,
    thumbnailHeight: 277.95,
    audioSource: "",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
  {
    title: "Waterbottle",
    src: "images/waterbottle.webp",
    thumbnail: "images/waterbottle.webp",
    thumbnailWidth: 339.15,
    thumbnailHeight: 521.7,
    audioSource: "",
    themes: { Appreciation, Perseverance },
    transcript:
      "This pandemic has been terrible in so many ways, but it has also offered the opportunity for self-reflection and self-growth. I bought this water bottle at the beginning of quarantine, and it represents the new mindset and  new goals that I had developed and have worked on since. First of all, it helped me improve my health— I decided to work out more often, drink more water, and eat healthier. I worked hard and my water bottle carried me through it, offering an ice cold reward whenever I succeeded. Second, I learned how to cook! Eating healthier meant learning what I should and shouldn’t put into my body, and how to find ways to control it. I still go for the occasional McDonalds or Taco Bell run, but also have created some of the most delicious meals I have ever had. Now, living apart from my parents,  I am so thankful that I took the time to learn. My water bottle has stayed with me throughout quarantine and will hopefully last me through the crazy, messed up year that is 2020 (it is also the longest I have had one without losing it, so that’s a good sign!). Here we go!",
    textSubmission: false,
  },
  {
    title: "Wineglass writer",
    src: "images/wineglass_writer.png",
    thumbnail: "images/wineglass_writer.png",
    thumbnailWidth: 254,
    thumbnailHeight: 338,
    audioSource: "",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
  {
    title: "Stationary Bike",
    src: "images/workout_machines.jpg",
    thumbnail: "images/workout_machines.jpg",
    thumbnailWidth: 196,
    thumbnailHeight: 403.2,
    audioSource: "",
    themes: { FeelingGrounded, HouseholdItems },
    transcript:
      "So, for my object, I chose the stationary bike that when my son came home from New York City after being laid off from his job, helped me move it into our garage. And in this period of COVID, that was the place that I went for retreat. It was the place I went to decompress, to kind of let go of all the stress of the isolation that I was feeling like so many people. And I went and listened to music, I listened to podcasts, heard news and information that I never would have if it weren't for COVID. And I looked out upon the natural world that was sitting in my driveway, which may sound really sort of circumscribed. But actually so much was going on right in front of me. All these baby rabbits was sort of traipse by, we never have had ground squirrels, or my daughter would call them chipmunks, in our neighborhood, but they suddenly appeared. And I saw them in my driveway and different kinds of woodpeckers and Cardinals, and even a hawk was flying overhead. And I kind of heard the sounds of the outside world, the sounds of nature, when I didn't have my headphones on, and the bike really kept me **grounded** and just allowed me to release so much of the toxicity of this moment and regroup. And you know, the garage itself became a special kind of retreat. My son who came home for three and a half months, because New York City was really a catastrophe, and he was living with multiple roommates in a bad part of Brooklyn. You know, having him home and to workout in that space was such an incredible gift. It's a gift I will take with me for the rest of my life. Max taught me how to lift weights, and we listened to his crazy metal music and talked and talked about the future, talked about kind of the present, our concerns, our hopes, we laughed. So it was a kind of space, the bike, my driveway, the garage that really was a refuge. And it may seem kind of strange and simple and basic, but it provided a world of relief.",
    textSubmission: false,
  },
  {
    title: "Yarn",
    src: "images/yarn.jpg",
    thumbnail: "images/yarn.jpg",
    thumbnailWidth: 302.4,
    thumbnailHeight: 302.4,
    audioSource: "audioStory/thread.mp3",
    themes: { HouseholdItems, HumanConnection },
    transcript:
      "Hello, I'm so the object that I'm adding to the archive is this collection of, I don't know, five or six embroidery threads that my friends and I bought when we were back in St. Louis and the pandemic hit and spring break was extended. So we were trying to find fun activities that we could do together. So we bought that unicorn card game, which I think unstable unicorns that's what it was an 8000 piece puzzle and lots of sanitary products and these threads so that we could make friendship bracelets. I guess as you can see, from this photo, we I never made my friendship bracelet. It was shipped the day before we all left for home. We and so all we did that night that we got it, we were excited least that we got it before we all left for home was that we picked all of these, we just sat on the sofa and decided which colors each of us was going to get. And my friends as they've always been doing made me go for more of a variety of colors that maybe I'd have picked on my own. And I think that's something that I really am very grateful for. Because I've been able to call people, friends who are very different from me, maybe in terms of lifestyle, and likes and dislikes and backgrounds and hobbies, priorities, whatever and but deep down I think we do share a very similar set of values, which I think has made us work so well together but also but also our the fact that we were so different from each other has really made me pushed me to experience life in ways that maybe I wouldn't have been able to one on my own. Anyways, I've tried a few try a few times to make the reset, but I don't even know where to start. And I've also been I guess quite bad about giving myself the time to sit down and not feel guilty about doing something just fun and very simple. And something like that is a lot easier when you're just with your friends. But um yes, this is maybe a not so special object. But I figured eventually I lose something like this to time as opposed to maybe my phone or my laptop which has been absolutely essential and in keeping me connected with my friends back in St Louis and, and whatever all over the world. But that that's it that's does my special object and I guess I'm gonna stop talking. Stop talking now.",
    textSubmission: false,
  },
  {
    title: "Zoom",
    src: "images/zoom.jpg",
    thumbnail: "images/zoom.jpg",
    thumbnailWidth: 410.1,
    thumbnailHeight: 234.9,
    audioSource: "",
    themes: [],
    transcript: "",
    textSubmission: false,
  },
]
